language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    
install:
    - sudo apt-get install -qq g++-4.8
    - export CC="gcc-4.8"
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    
script: cd src && make clean all
